package net.paulhertz.pixelaudio.example;

import processing.core.PApplet;
import processing.core.PImage;
import net.paulhertz.pixelaudio.*;

/**
 * This is the Starter example with animation added. In the LookupTables example we showed how to 
 * rotate an array along the signal path and then write it to the display. When we work with 
 * large arrays, shifting numbers for every animation step is not an efficient procedure. Instead,
 * we just shift an index into an array and then copy the pixels to the display using the shifted
 * index. We'll use this technique in all our examples. 
 */
public class SimpleAnimation extends PApplet {
	PixelAudio pixelaudio;        // the library that we need to load in setup()
	HilbertGen hGen;              // a PixelMapGen child class for making Hilbert curves
	PixelAudioMapper mapper;      // a class that uses a PixelMapGen ("gen", for short) to map audio samples to RGB pixels
	PImage mapImage;              // a bitmap image for display
	PImage baseImage;             // a reference image, unchanging, used as source for animation
	int[] spectrum;               // an array of colors that will be written along the "signal path" in mapImage
	int shift = 64;               // amount we shift for each animation step
	int totalShift = 0;           // total amount we have shifted the image
	boolean isAnimating = false;  // toggle for animation
	

	public static void main(String[] args) {
		PApplet.main(new String[] { SimpleAnimation.class.getName() });
	}

	public void settings() {
		  size(512, 512);                          // Hilbert curves require dimensions that are powers of 2. 		
	}

	// PixelAudio sketches typically begin like this.
	public void setup() {
	  pixelaudio = new PixelAudio(this);           // 1. initialize PixelAudio library
	  hGen = new HilbertGen(width, height);        // 2. create a PixelMapGen: here it's the Hilbert curve generator
	  mapper = new PixelAudioMapper(hGen);         // 3. initialize a PixelAudioMapper object with the gen
	  mapImage = createImage(width, height, RGB);  // 4. create an image for display
	  // At this point, we might load audio, but we'll leave that for later.
	  // Right now, let's just look at the pattern the Hilbert curve makes in the display image.
	  // We'll do this frequently in example code, since it shows how an audio signal maps to the image. 
	  mapImage.loadPixels();
	  spectrum = getColors(mapper.getSize());
	  // To show the colors, we call mapper.plantPixels(...). Mapper knows the geometry of the 
	  // signal path generated by hGen. PlantPixels(...) copies an array of RGB colors to the signal path
	  // of a supplied image pixels array: the colors array leaves a rainbow color trail.
	  mapper.plantPixels(spectrum, mapImage.pixels, 0, mapper.getSize());
	  mapImage.updatePixels();
	  baseImage = mapImage.copy();    // 5. initialize baseImage, the reference image for pixel-shifting animation
	  showHelp();
	}

	/**
	 * Creates an array of colors in rainbow (spectrum) order.
	 * @param size    size of the desired array
	 * @return an array of colors in rainbow (spectrum) order
	 */
	public int[] getColors(int size) {
	  int[] colorWheel = new int[size];
	  pushStyle();
	  colorMode(HSB, colorWheel.length, 100, 100);
	  int h = 0;
	  for (int i = 0; i < colorWheel.length; i++) {
	    colorWheel[i] = color(h, 66, 66);
	    h++;
	  }
	  popStyle();
	  return colorWheel;
	}

	public void draw() {
	  image(mapImage, 0, 0);
	  if (isAnimating) animate();
	}
	
	public void animate() {
		totalShift += shift;
		mapImage.loadPixels();
		// PixelAudioMapper has the method we need
		mapper.copyPixelsAlongPathShifted(baseImage.pixels, mapImage.pixels, totalShift);
		mapImage.updatePixels();
	}

	public void keyPressed() {
	  switch(key) {
	  case 'a': // toggle animation
		  isAnimating = !isAnimating;
		  println(isAnimating ? "-- animation is running" : "-- animation is paused");
		  break;
	  case 'h': // print help to the console
	    showHelp();
	    break;
	  default:
	    break;
	  }
	}
	
	public void showHelp() {
		println(" * Press 'a' to toggle animation.");
		println(" * Press 'h' to print help to the console.");
	}
	
}
