/*
 *  Copyright (c) 2024 - 2025 by Paul Hertz <ignotus@gmail.com>
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Library General Public License as published
 *   by the Free Software Foundation; either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package net.paulhertz.pixelaudio.sampler;

/**
 * Backend engine contract for sampler implementations.
 * Allows swapping implementations without changing higher layers.
 */
public interface PASampler {
	
    /**
     * Play command with all the useful arguments in standard order.
     * 
     * @param samplePos    index into the buffer to start sampling 
     * @param sampleLen    requested note-window length in source-buffer samples
     * @param amplitude    maximum amplitude of signal generated by the sampler, linear value
     * @param env          ADSR style envelope for the entire event
     * @param pitch        pitch multiplier, where 1.0f implies pitch is unchanged and all samples are read
     * @param pan          location of audio event in stereo field, -1.0f = left, 0.0f = center, 1.0f = right
     * @return             actual duration of event in output samples, including envelope release
     */
    int play(int samplePos, int sampleLen, float amplitude, ADSRParams env, float pitch, float pan);

    /**
     * Schedules playback at an absolute sample time on this sampler's audio clock.
     *
     * @param samplePos    index into the buffer to start sampling
     * @param sampleLen    requested note-window length in source-buffer samples
     * @param amplitude    maximum amplitude of signal generated by the sampler, linear value
     * @param env          ADSR style envelope for the entire event
     * @param pitch        pitch multiplier, where 1.0f implies pitch is unchanged
     * @param pan          location of audio event in stereo field, -1.0f = left, 0.0f = center, 1.0f = right
     * @param startSample  absolute sample index on this sampler's clock
     */
    void startAtSampleTime(int samplePos, int sampleLen, float amplitude,
            ADSRParams env, float pitch, float pan, long startSample);

    /**
     * Schedules playback after a delay in samples relative to this sampler's current audio clock.
     *
     * @param samplePos      index into the buffer to start sampling
     * @param sampleLen      requested note-window length in source-buffer samples
     * @param amplitude      maximum amplitude of signal generated by the sampler, linear value
     * @param env            ADSR style envelope for the entire event
     * @param pitch          pitch multiplier, where 1.0f implies pitch is unchanged
     * @param pan            location of audio event in stereo field, -1.0f = left, 0.0f = center, 1.0f = right
     * @param delaySamples   delay from the current sample time
     */
    void startAfterDelaySamples(int samplePos, int sampleLen, float amplitude,
            ADSRParams env, float pitch, float pan, long delaySamples);

    /**
     * Returns this sampler's current audio-thread sample clock.
     *
     * @return absolute sample cursor maintained by the sampler
     */
    long getCurrentSampleTime();

    /** Clears scheduled starts that have not fired yet. */
    void clearScheduled();

    /**
     * Sets whether new sampler voices wrap source-buffer reads at the buffer end.
     *
     * <p>Wrapping is distinct from looping: a wrapped one-shot still plays for its requested
     * duration and envelope, but sample reads that pass the end of the source buffer continue
     * from the beginning.</p>
     *
     * @param wrapAround true to wrap source-buffer reads for newly triggered voices
     */
    void setWrapAround(boolean wrapAround);

    /**
     * Reports whether new sampler voices wrap source-buffer reads at the buffer end.
     *
     * @return true when source-buffer wrapping is enabled
     */
    boolean isWrapAround();

    /**
     * Returns true if any currently active voice is looping.
     *
     * @return true if one or more voices are looping
     */
    boolean isLooping();

	/** Stops all voices immediately. */
	void stopAll();
	
	/** Releases all voices through their envelopes. */
	void releaseAll();

	/**
	 * Updates the source-buffer sample rate.
	 *
	 * <p>This is distinct from the audio device or Minim {@code UGen} sample rate.
	 * It controls how source-buffer sample positions are interpreted for playback speed.
	 * Envelope timing uses the output sample rate instead.</p>
	 *
	 * @param newRate   new source-buffer playback sample rate in Hz
	 */
	default void setBufferSampleRate(float newRate) {
		// update source-buffer sample rate
	}

	/**
	 * Updates the audio output sample rate. This is the clock for envelopes,
	 * scheduling, and returned event durations.
	 *
	 * @param newRate new audio output sample rate in Hz
	 */
	default void setOutputSampleRate(float newRate) {
		// Backward-compatible no-op for sampler implementations that predate
		// separate source-buffer and output clocks.
	}
	
	/**
	 * Replaces the sampler source buffer.
	 *
	 * @param buffer   mono source sample buffer
	 */
	public void setBuffer(float[] buffer);
	
	/**
	 * Replaces the sampler source buffer and its intrinsic sample rate.
	 *
	 * @param buffer   mono source sample buffer
	 * @param bufferSampleRate sample rate of the source buffer in Hz
	 */
	public void setBuffer(float[] buffer, float bufferSampleRate);
	
}
