import net.paulhertz.pixelaudio.*;

/**
 * Basics of setting up a PixelAudio sketch with a bitmap color array.
 */

// PixelAudio sketches typically require these variables
PixelAudio pixelaudio;        // the library that we need to load in setup()
HilbertGen hGen;              // a PixelMapGen for generating a Hilbert curve signal path
PixelAudioMapper mapper;      // a class initialized with a PixelMapGen, for mapping and transcoding audio samples and RGB pixels
PImage mapImage;              // a bitmap image for display
int[] spectrum;               // an array of colors to write along the "signal path" in mapImage


public void settings() {
  size(512, 512);                          // Hilbert curves require dimensions that are powers of 2.
}

// PixelAudio sketches typically begin like this.
public void setup() {
  pixelaudio = new PixelAudio(this);           // 1. initialize PixelAudio library
  hGen = new HilbertGen(width, height);        // 2. create a PixelMapGen, hGen
  mapper = new PixelAudioMapper(hGen);         // 3. create PixelAudioMapper mapper with hGen
  mapImage = createImage(width, height, RGB);  // 4. create an image for display
  // At this point, we might load audio, but we'll leave that for later.
  // Right now, let's just look at the pattern the Hilbert curve makes in the display image.
  // We'll do this frequently in example code, since it shows how an audio signal maps to the image.
  mapImage.loadPixels();                       // 5. prepare to set mapImage.pixels
  spectrum = getColors(mapper.getSize());      // 6. generate an RGB pixel array
  // To show the colors, we call mapper.plantPixels(...). Mapper knows the geometry of the
  // signal path generated by hGen. PlantPixels(...) copies an array of RGB colors to the signal path
  // of a supplied image pixels array: the colors array leaves a rainbow color trail.
  mapper.plantPixels(spectrum, mapImage.pixels, 0, mapper.getSize());
  mapImage.updatePixels();
}

/**
 * Creates an array of colors in rainbow (spectrum) order.
 * @param size    size of the desired array
 * @return an array of colors in rainbow (spectrum) order
 */
public int[] getColors(int size) {
  int[] colorWheel = new int[size];
  pushStyle();
  colorMode(HSB, colorWheel.length, 100, 100);
  int h = 0;
  for (int i = 0; i < colorWheel.length; i++) {
    colorWheel[i] = color(h, 66, 66);
    h++;
  }
  popStyle();
  return colorWheel;
}

public void draw() {
  image(mapImage, 0, 0);
}

public void keyPressed() {
  switch(key) {
  case 'h':
    println("---- no help whatsoever ----");
    break;
  default:
    break;
  }
}
