/*----------------------------------------------------------------*/
/*                                                                */
/*                     BEGIN AUDIO METHODS                        */
/*                                                                */
/*----------------------------------------------------------------*/

/**
 * CALL IN SETUP()
 */
public void initAudio() {
  minim = new Minim(this);
  // use the getLineOut method of the Minim object to get an AudioOutput object
  this.audioOut = minim.getLineOut(Minim.STEREO, 1024, sampleRate);
  this.setAudioGain(outputGain);
  this.audioBuffer = new MultiChannelBuffer(mapSize, 1);
  // ADSR envelope with maximum amplitude, attack Time, decay time, sustain level, and release time
  samplerEnv = new ADSRParams(maxAmplitude, attackTime, decayTime, sustainLevel, releaseTime);
  ensureSamplerReady();
  this.renderSignal();
  timeLocsArray = new ArrayList<TimedLocation>();     // initialize mouse event tracking array
}

/**
 * Prepares Sampler instruments and assets
 */
void ensureSamplerReady() {
  if (pool != null) pool.setBuffer(audioBuffer);
  else pool = new PASamplerInstrumentPool(audioBuffer, sampleRate, poolSize, samplerMaxVoices, audioOut, samplerEnv);
  pool.setWrapAround(isWrapAround);
  pool.setGain(samplerGain);
}

/**
 * Bottleneck "commit" method for audio state.
 *
 * Takes an arbitrary input signal and installs it as the canonical audio signal
 * used by the application. This method:
 *
 *  - Resizes/pads/truncates the input to mapper.getSize()
 *  - Copies the data to ensure no external aliasing
 *  - Updates audioSignal (canonical signal handled by application code)
 *  - Updates audioBuffer (audio buffer used by Minim audio library methods)
 *  - Propagates the buffer to active instruments: edit for your own instruments
 *
 * This is the ONLY method that should mutate the global audio signal state.
 *
 * In PixelAudio examples, the signal is typically loaded from a file, but
 * it could also be signal cached in memory, a signal generated by code, audio
 * captured live, etc.
 *
 * @param sig                 an audio signal
 * @param bufferSampleRate    audio sample rate for sig,
 *                            usually obtained when reading from an audio file
 */
void updateAudioChain(float[] sig, float bufferSampleRate) {
  // 0) Decide target length (make this a single source of truth)
  int targetSize = mapper.getSize();
  if (targetSize <= 0) return;
  // 1) Ensure audioBuffer matches target
  float[] canonical = new float[targetSize];
  if (sig != null) {
    System.arraycopy(sig, 0, canonical, 0, Math.min(sig.length, targetSize));
  }
  // 3) Set audioSignal and other audio arrays
  audioSignal = canonical;
  audioLength = targetSize;
  // 4) Store signal in audioBuffer
  if (audioBuffer == null || audioBuffer.getBufferSize() != targetSize) {
    audioBuffer = new MultiChannelBuffer(targetSize, 1);
  }
  audioBuffer.setChannel(0, canonical);
  // 5) Propagate into synths (adjust to your actual API)
  if (pool != null) {
    pool.setBuffer(audioBuffer, bufferSampleRate);
    pool.setWrapAround(isWrapAround);
  }
}

void updateAudioChain(float[] sig) {
  // updateAudioChain(sig, audioOut.sampleRate());
  updateAudioChain(sig, wavesynth.getSampleRate());
}

/**
 * Save audio buffer to a file called "wavesynth_(wsIndex).wav".
 */
public void saveToAudio() {
  float oldRate = wavesynth.getSampleRate();
  wavesynth.setSampleRate(this.sampleRate);
  float[] exportSig = wavesynth.renderAudioRaw(step);
  exportSig = WaveSynth.normalize(exportSig, 0.9f);
  try {
    saveAudioToFile(exportSig, sampleRate, "wavesynth_"+ wsIndex +".wav");
  }
  catch (IOException e) {
    println("--->> There was an error outputting the audio file wavesynth.wav "+ e.getMessage());
  }
  catch (UnsupportedAudioFileException e) {
    println("--->> The file format is unsupported "+ e.getMessage());
  }
  finally {
    wavesynth.setSampleRate(oldRate);
    audioDirty = true;
    refreshAudioIfDirty();
  }
}

/**
 * Calls WaveSynth to render a audio sample array derived from the same math that creates the image,
 * then loads the derived audio data to audioBuffer, ready to be played.
 */
public void renderSignal() {
  mapImage = renderFrame(step);
  float[] sig = wavesynth.renderAudioRaw(step);           // get the signal "as is" from WaveSynth
  sig = WaveSynth.normalize(sig, 0.9f);        // normalize samples to the range (-0.9f, 0.9f)
  this.updateAudioChain(sig);
  // println("--->> copied audio signal to audio buffer");
}

/**
 * Plays an audio sample with WFSamplerInstrument and custom ADSR.
 *
 * @param samplePos    position of the sample in the audio buffer
 * @param samplelen    length of the sample (will be adjusted)
 * @param amplitude    amplitude of the sample on playback
 * @param env          an ADSR envelope for the sample
 * @return the calculated sample length in samples
 */
public int playSample(int samplePos, int samplelen, float amplitude, ADSRParams env) {
  int[] coords = mapper.lookupImageCoordShifted(samplePos, 0);
  float pan = PApplet.map(coords[0], 0, width-1, -1.0f, 1.0f);
  samplelen = pool.playSample(samplePos, (int) samplelen, amplitude, env, 1.0f, pan);
  // return the length of the sample
  return samplelen;
}

/**
 * Plays an audio sample with WFSamplerInstrument and default ADSR.
 *
 * @param samplePos    position of the sample in the audio buffer
 * @param samplelen    length of the sample (will be adjusted)
 * @param amplitude    amplitude of the sample on playback
 * @return the calculated sample length in samples
 */
public int playSample(int samplePos, int samplelen, float amplitude) {
  return playSample(samplePos, samplelen, amplitude, samplerEnv);
}

public int calcSampleLen() {
  float vary = 0;
  // skip the fairly rare negative numbers
  while (vary <= 0) {
    vary = (float) PixelAudio.gauss(1.0, 0.0625);
  }
  samplelen = (int)(abs((vary * this.noteDuration) * sampleRate / 1000.0f));
  // println("---- calcSampleLen samplelen = "+ samplelen +" samples at "+ sampleRate +"Hz sample rate");
  return samplelen;
}

/**
 * Run the animation for audio events.
 */
public void runTimeArray() {
    int currentTime = millis();
    timeLocsArray.forEach(tl -> {
        tl.setStale(tl.eventTime() < currentTime);
        if (!tl.isStale()) {
	int x = isFitToScreen ? sampleToScreenX(tl.getX()) : tl.getX();
	int y = isFitToScreen ? sampleToScreenY(tl.getY()) : tl.getY();
	drawCircle(x, y);
        }
    });
    timeLocsArray.removeIf(TimedLocation::isStale);
}

/**
 * Draws a circle at the location of an audio trigger (mouseDown event).
 * @param x        x coordinate of circle
 * @param y        y coordinate of circle
 */
public void drawCircle(int x, int y) {
  //float size = isRaining? random(10, 30) : 60;
  fill(color(233, 220, 199));
  noStroke();
  circle(x, y, 60);
}
